# Generated by Django 4.2.4 on 2023-08-11 19:32

from django.db import migrations


def dump_permissions(apps, schema_editor):
    MyPermission = apps.get_model("account", "MyPermission")
    permissions = [
        "create_post",
        "delete_post",
        "edit_post",
        "user_management",
        "site_settings",
    ]
    for permission in permissions:
        MyPermission.objects.create(title=permission)


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_mypermission"),
    ]

    operations = [
        migrations.RunPython(dump_permissions),
    ]
