# Generated by Django 4.2.4 on 2023-08-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0005_alter_myuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='account.mypermission'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
